version: "3.9"

services:

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespwd
      - POSTGRES_DB=database
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: ./local.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./api/app:/workdir/app
    env_file:
      - ./api/.env

volumes:
  db_data:
