"""empty message

Revision ID: 2c9e721e2291
Revises: 3192427faed0
Create Date: 2024-03-29 07:16:23.992537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9e721e2291'
down_revision: Union[str, None] = '3192427faed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'threads', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threads', type_='foreignkey')
    op.drop_column('threads', 'user_id')
    # ### end Alembic commands ###
